### ISSUE TITLE
Apk size

### ISSUE THREAD

**Issue by vishalknishad** [appodeal/Appodeal-Flutter-Plugin#12]
After adding this package, apk size jumped from 28mb to 66mb 😰. What size can I expect after publishing as bundle to Google Play?

**Comment by da2gl** [comment]
@vishalknishad Hi.
Do you use R8 and release build for your app? Because 66mb sounds very sad.
I'm building our demo app and it's pretty lightweight (Despite the fact that it includes many ad networks from Appodeal SDK and a Flutter engine).

```
Running Gradle task 'bundleRelease'...                             51,3s
✓ Built build/app/outputs/bundle/release/app-release.aab (31.4MB).
```

**Comment by davidgalarza** [comment]
Same issue here my app-release.abb was from 30MB without appodeal SDK to 51.2MB

**Comment by vishalknishad** [comment]
I found the solution

add this tag on you AndroidManifest.xml file
```android:extractNativeLibs="true"```

example:

```
<application
    android:extractNativeLibs="true"
    ... >
</application>```
