### ISSUE TITLE
after upd to flutter 3

### ISSUE THREAD

**Issue by BlackJet1** [appodeal/Appodeal-Flutter-Plugin#16]
## Steps to Reproduce

e: E:\Flutter\.pub-cache\hosted\pub.dartlang.org\stack_appodeal_flutter-1.2.0\android\src\main\kotlin\com\appodeal\appodeal_flutter\AppodealAdViewFactory.kt: (9, 10): Class 'AppodealAdViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Cont
ext?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: E:\Flutter\.pub-cache\hosted\pub.dartlang.org\stack_appodeal_flutter-1.2.0\android\src\main\kotlin\com\appodeal\appodeal_flutter\AppodealAdViewFactory.kt: (12, 5): 'create' overrides nothing

FAILURE: Build failed with an exception.
 
* What went wrong:
Execution failed for task ':stack_appodeal_flutter:compileReleaseKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by imariman** [comment]
Is this repo still active? We can't run our Android app because of this very simple issue since last week.

**Comment by mgazisalik** [comment]
https://docs.flutter.dev/development/platform-integration/platform-views

I talked about this with Appodeal support team. They said it can take a few weeks to update the package for flutter 3.

**Comment by da2gl** [comment]
Hi @BlackJet1, @imariman, @mgazisalik .
We have started updating the plugin for 3.0 compatibility.
Have a nice day.

**Comment by Defuera** [comment]
Fix is here https://github.com/appodeal/Appodeal-Flutter-Plugin/pull/18

**Comment by da2gl** [comment]
@Defuera Thanks for your PR. We created new release from your template fix.

@BlackJet1, @imariman, @mgazisalik
new version already on [pub.dev](https://pub.dev/packages/stack_appodeal_flutter)

**Comment by wandermonk1** [comment]
I updated the new package still my app is crashing.
Working fine if I commented out the follwowing line in App level build.graddle 

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
//    implementation 'com.appodeal.ads:sdk:2.11.0.+'
}

Please help me
