### ISSUE TITLE
Full width banner

### ISSUE THREAD

**Issue by atelog** [appodeal/Appodeal-Flutter-Plugin#17]
## Steps to Reproduce

1. Make sure smart banner are enabled `Appodeal.setSmartBanners(true);`
2. Add a banner inside a container ```
AppodealBanner(
                    adSize: AppodealBannerSize.BANNER,
                    placement: "default"
                  )
                  ```

**Expected results:** Banner to fill the full width if is possible

**Actual results:** Baner has a fixed size


<details>
  <summary>Image</summary>

![IMG_3584](https://user-images.githubusercontent.com/36562834/169718293-03623f0f-78cb-4a3c-bdce-27b4b5b8b05c.PNG)

</details>

**Comment by da2gl** [comment]
Hello @atelog .
Thanks for the issue. We started working on changing the banner behavior for the plugin.
Have a nice day.

**Comment by atelog** [comment]
@da2gl 
Also, sometimes, the banner is cut and the content is not fully visible

 
![image](https://user-images.githubusercontent.com/36562834/171529832-d17f4315-b435-4617-bb79-d06c89ec822c.png)

**Comment by da2gl** [comment]
@atelog Hello. Right now we don't support smart banners for Ad View case. But we fixed banner clipping in the latest update.
