### ISSUE TITLE
Maybe re-license the library as MIT, BSD or Apache?

### ISSUE THREAD

**Issue by wildwaffle** [appodeal/Appodeal-Flutter-Plugin#2]
I see the library uses the GPL. Quite unusual for pub.dev.

Do you expect every Appodeal client who decided to use this library to re-license their entire application under the GPL and make their source code public? Or should they overlook the license and become violators of copyright laws? It's hard to believe in both.

**Comment by da2gl** [comment]
@wildwaffle Thanks for your issue.
We have changed the license to use the product.
