### ISSUE TITLE
updateConsent method cause crash on iOS

### ISSUE THREAD

**Issue by mgazisalik** [appodeal/Appodeal-Flutter-Plugin#22]
I am getting this error when I call Appodeal.updateConsent(null).

`stack_appodeal_flutter/SwiftAppodealFlutterPlugin.swift:87: Fatal error: Unexpectedly found nil while unwrapping an Optional value.`

**Comment by da2gl** [comment]
@mgazisalik Hello!
We have released a new version of the SDK in which we have changed update consent logic. Please, try our new version!
If you have any questions/issues I will be glad to answer.
Have a good day.
