### ISSUE TITLE
How to know whether users agreed consent or not?

### ISSUE THREAD

**Issue by phamanhminh1208** [appodeal/Appodeal-Flutter-Plugin#25]
I'm new user of Appodeal Flutter (ver 3.0.0) and I don't understand how to know if the user agrees to the terms of the consent or not because onClosed() callback of Appodeal.showConsentForm doesn't return anything. 

Can you tell me how to know that. Many thanks.

**Comment by AntonZarytski** [comment]
Hello @phamanhminh1208! Thanks for let us know. 
Could you write to our support team? We will definitely solve your question.  
You can do this in the chat directly in your personal Appodeal account or contact by email support@appodeal.com

**Comment by phamanhminh1208** [comment]
> Hello @phamanhminh1208! Thanks for let us know. Could you write to our support team? We will definitely solve your question. You can do this in the chat directly in your personal Appodeal account or contact by email [support@appodeal.com](mailto:support@appodeal.com)

thanks for your reply. I'm going to contact with your support team.
