### ISSUE TITLE
Appodeal Flutter Interstitial Ads problem on Android

### ISSUE THREAD

**Issue by galiperkin** [appodeal/Appodeal-Flutter-Plugin#27]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
4. ... 

**Expected results:** 
Initialize Appodeal on android
**Actual results:** 
E/MethodChannel#appodeal_flutter(30781): Failed to handle method call
E/MethodChannel#appodeal_flutter(30781): java.lang.ClassCastException: java.lang.Integer cannot be cast to java.util.List
E/MethodChannel#appodeal_flutter(30781): 	at com.appodeal.appodeal_flutter.AppodealFlutterPlugin.initialize(AppodealFlutterPlugin.kt:137)
E/MethodChannel#appodeal_flutter(30781): 	at com.appodeal.appodeal_flutter.AppodealFlutterPlugin.onMethodCall(AppodealFlutterPlugin.kt:50)
E/MethodChannel#appodeal_flutter(30781): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#appodeal_flutter(30781): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#appodeal_flutter(30781): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
E/MethodChannel#appodeal_flutter(30781): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/MethodChannel#appodeal_flutter(30781): 	at android.os.Handler.handleCallback(Handler.java:873)
E/MethodChannel#appodeal_flutter(30781): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#appodeal_flutter(30781): 	at android.os.Looper.loop(Looper.java:201)
E/MethodChannel#appodeal_flutter(30781): 	at android.app.ActivityThread.main(ActivityThread.java:6810)
E/MethodChannel#appodeal_flutter(30781): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#appodeal_flutter(30781): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/MethodChannel#appodeal_flutter(30781): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
flutter analyze
Analyzing repository
No issues found! (ran in 4.0s)
```

```
flutter doctor -v
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.5 21G72 darwin-x64, locale tr-TR)
    • Flutter version 3.0.0 at /Users/____/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (4 months ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/_____/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Redmi Note 6 Pro (mobile) • b1a0467 • android-arm64  • Android 9 (API 28)
    • macOS (desktop)           • macos   • darwin-x64     • macOS 12.5 21G72 darwin-x64
    • Chrome (web)              • chrome  • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by galiperkin** [comment]
Hi there, I cannot show interstitial ads on android with Appodeal Flutter. I can show AppodealAdType.RewardedVideo type ads but I cannot show AppodealAdType.Interstitial type ads on android. There is no issue on iOS.

**Comment by da2gl** [comment]
Hello @galiperkin! 
Thanks for let us know.
Can you attach a snippet code of how you initialize Appodeal SDK and how you call the show method?
