### ISSUE TITLE
Call validateInAppPurchase with a build distributed via Firebase app distro doesn't execute any callbacks

### ISSUE THREAD

**Issue by PickleCubeSoftwareLtd** [appodeal/Appodeal-Flutter-Plugin#34]
## Steps to Reproduce

Call `validateInAppPurchase` with a build distributed via Firebase app distro.

**Expected results:** 
Validate the transaction successfully - it should be able to use the sandbox/test transactions on Google Play?

**Actual results:** 
The callbacks for either `onInAppPurchaseValidateSuccess` or `onInAppPurchaseValidateFail` are **not** called

I am trying to use a completer to aid with async calls that I make (this works for my custom server side validation by the way) 
Is there any way to submit a purchase without requiring Appodeal to verify it?

      final completer = Completer<bool?>();

      try {
        Appodeal.validateInAppPurchase(
          purchase: appodealPurchase,
          onInAppPurchaseValidateSuccess: (purchase, errors) {
            completer.complete(true);
          },
          onInAppPurchaseValidateFail: (purchase, errors) {
            completer.complete(false);
          },
        );
      } on Exception catch (exception, stack) {
        completer.complete(null);
      }

      return completer.future;

**Comment by da2gl** [comment]
@PickleCubeSoftwareLtd Hello. 
In-App purchase tracking will work only with connection with Adjust/Appsflyer.
You can find more information about `validateInAppPurchase` [here](https://github.com/appodeal/Appodeal-Flutter-Plugin#tracking-in-app-purchases) or [native android doc](https://wiki.appodeal.com/en/android/get-started/advanced/in-app-purchases) and [native ios doc](https://wiki.appodeal.com/en/ios/get-started/advanced/in-app-purchases). 
Tell me, do you use Adjust/Appsflyer to validate purchases?

For faster resolution of the following issues, you can also write to us in support in the chat directly in your personal Appodeal account or contact by email [support@appodeal.com](mailto:support@appodeal.com)
