### ISSUE TITLE
Flutter Interstitial ad is showing but RewardedVideo not showing

### ISSUE THREAD

**Issue by serhaterfidan** [appodeal/Appodeal-Flutter-Plugin#38]
Appodeal.show(AppodealAdType.RewardedVideo);
                  Appodeal.setRewardedVideoCallbacks(
                    onRewardedVideoFinished: (amount, reward) => {
                      videoNumbers.add(widget.index)
                    },
                  );

**Comment by da2gl** [comment]
@serhaterfidan Hi, could you attach more information to this issue for our further research:
1. Steps to Reproduce
2. Full code sample
3. Logs (`tag:Appodeal`)
4. `Flutter Doctor` logs

Thanks.
