### ISSUE TITLE
ConsentManager - Android

### ISSUE THREAD

**Issue by devuserPP** [appodeal/Appodeal-Flutter-Plugin#5]
`ConsentManager.showAsActivityConsentForm() `and `ConsentManager.loadConsentForm();` from example does not work.
Same for `showAsDialogConsentForm()`, always error `onConsentFormError error - com.explorestack.consent.exception.ConsentManagerInconsistentException@ac3c7f4
`var consentStatus = await ConsentManager.getConsentStatus();` return `throw MissingPluginException('No implementation found for method $method on channel $name');`

` Can you fix it?

**Comment by da2gl** [comment]
@devuserPP Hello!
Did you call `loadConsentForm` after get result callback in `requestConsentInfoUpdate`? 
Can you attach all yours logs? and describe consent window flow? (ex. requestConsentInfoUpdate -> onConsentInfoUpdated- > should show? -> loadConsentForm -> ...) 
Thanks.

**Comment by road12runner** [comment]
Hello,  
I got  an exception  on android: 
D/Consent Manager [IO]( 8390): Network Error: java.net.UnknownHostException: Unable to resolve host "a.appbaqend.com": No address associated with hostname(com.android.okhttp.internal.huc.HttpURLConnectionImpl:https://a.appbaqend.com/consent/check)
I/gralloc4( 8390): register: id=1b700000076
I/gralloc4( 8390): register: id=1b700000077
I/flutter ( 8390): onFailedToUpdateConsentInfo error - com.explorestack.consent.exception.ConsentManagerNetworkException@9eedc73


in IOS   ConsentManager works fine.   
Any idea how to fix that?
Thanx

**Comment by da2gl** [comment]
@devuserPP Hello!
Are you still having a problem with Consent Manager?

**Comment by da2gl** [comment]
@devuserPP Hello.
Please add code example, application logs, and `flutter doctor -v` logs by section:
<details>
<summary>Code sample</summary>
</details>

<details>
  <summary>Application Logs</summary>
</details>

<details>
  <summary>Flutter Doctor Logs</summary>
</details>

**Comment by da2gl** [comment]
@devuserPP Hello! 
We have released a new version of the SDK in which we have changed update consent logic. Please, try our new version!
If you have any questions/issues I will be glad to answer.
Have a good day.
