### ISSUE TITLE
 Error (Xcode): Undefined symbol: __swift_FORCE_LOAD_$_swiftCompatibility56

### ISSUE THREAD

**Issue by desaivishal11** [appodeal/Appodeal-Flutter-Plugin#50]
While upgrading to newer version getting below error.

 Error (Xcode): Undefined symbol: __swift_FORCE_LOAD_$_swiftCompatibility56

dependencies:
  stack_appodeal_flutter: 3.2.0-beta.1

**Comment by da2gl** [comment]
@desaivishal11 Hi, could you attach more information to this issue for our further research:
1. `flutter run --verbose` logs
2. `flutter analyze` logs
3. `flutter doctor -v` logs

For faster resolution of the issues, you can also write to us in support in the chat directly in your personal Appodeal account or contact by email [support@appodeal.com](mailto:support@appodeal.com).

Thank you.

**Comment by da2gl** [comment]
Hello @desaivishal11.
If you still have a problem, you can create a new issue or comment here.
