### ISSUE TITLE
Google Play Rejection because of SDK: MyTarget com.my.target:mytarget-sdk

### ISSUE THREAD

**Issue by oliverbytes** [appodeal/Appodeal-Flutter-Plugin#51]
## Steps to Reproduce

Upload a new binary using Appodeal SDK 3.1.3

Below is the full rejection email:
[Google Play Rejection.pdf](https://github.com/appodeal/Appodeal-Flutter-Plugin/files/13293944/Google.Play.Rejection.pdf)

> We found an issue in the following area(s):
> 
> Version code 42:
> SDK: MyTarget com.my.target:mytarget-sdk
> To bring your app into compliance, follow these steps:
> 
> Verify that your app accesses, collects, uses, and shares (including with SDKs) device location only for approved purposes and in compliance with the applicable prominent disclosure and consent requirements of the above-mentioned policies. Do not enable SDK data collection if it violates these requirements.
> Submit an appeal of this rejection and attach evidence (e.g. screenshots or a video demonstration of the in-app prominent disclosure and consent experience) of your compliance with the Prominent Disclosure requirements.
> 
> In the alternative, you may consider removing the SDK code designed to collect personal and sensitive user data by default, or moving to an alternative SDK or version which includes the appropriate technical mechanism to ensure that end user consent information collected by apps is honored. You may consider upgrading to a policy-compliant version of this SDK, if available from your SDK provider or removing the SDK. Google is unable to endorse or recommend any third party software.
> MyTarget com.my.target:mytarget-sdk: Consider upgrading to a policy-compliant version of the SDK if available from your SDK provider, or removing the SDK.
>

**Comment by da2gl** [comment]
Hello @oliverbytes.
You can use our latest [release](https://github.com/appodeal/Appodeal-Flutter-Plugin/releases/tag/v3.2.0-beta.2) #52 
Thank you.
