### ISSUE TITLE
[Bug report] Namespace is not specified. (A problem occurred configuring project ':stack_appodeal_flutter'.)

### ISSUE THREAD

**Issue by raspberry-jenshen** [appodeal/Appodeal-Flutter-Plugin#54]
Hello,
Could you add namespace support for this plugin?

In order to support gradle version 8>

```
android {
  // Conditional for compatibility with AGP <4.2.
  if (project.android.hasProperty("namespace")) {
    namespace 'io.flutter.plugins.firebase.messaging'
  }
```
With a different namespace of course :)

https://github.com/fluttercandies/flutter_image_compress/issues/265

**Comment by da2gl** [comment]
@raspberry-jenshen Hello. Thanks for your report. We take it to work.

**Comment by da2gl** [comment]
#55
