### ISSUE TITLE
How display more than one ad in the Widgets list?

### ISSUE THREAD

**Issue by nathanael540** [appodeal/Appodeal-Flutter-Plugin#65]
It is impossible to display more than one ad of the same type in the Widgets list.

I'm implementing a listview but the items disappear after loading more than one item of the same size

![Screenshot](https://img001.prntscr.com/file/img001/1iArJoJaQMuNTG-MyoxVaw.png)

**Comment by da2gl** [comment]
@nathanael540 Hello.
We only support Banner and MREC ad view. Unfortunately, for current formats it is impossible to display multiple ads according to the store’s rules for displaying ads, and the implementation of our plugin does not allow this.
I think Native ad type support in the plugin will solve your problem. We are working on it.
