### ISSUE TITLE
Important questions not mentioned in the documentation

### ISSUE THREAD

**Issue by deakjahn** [appodeal/Appodeal-Flutter-Plugin#71]
Am I correct with these three assumptions?

1. There is no way to test it before actually committing ourselves and getting an app key. Even the test mode expects a valid key.
2. Our apps will be quite a bit larger with very many SDK's bundled together and added.
3. The build process (which is not the fastest in the first place) becomes terribly slow. Integration adds minutes to the process.

This is unfortunate. I had high hopes but with these circumstances, well...

**Comment by da2gl** [comment]
@deakjahn Hi,
1. You can try our demo app with test mode and test credentials, you don't need to create an account and get a key in advance.
2. Appodeal SDK Flutter package install only core, you can configure ad network libraries and service libraries at your discretion.
3. It also depends on the second point
