### ISSUE TITLE
Can't build project for iPhone simulator

### ISSUE THREAD

**Issue by JiyadAhammad** [appodeal/Appodeal-Flutter-Plugin#78]
i' m facing issue while building ios build 
app taking too much time load and not complete the build 

already added all integration documents and files in pod and info.plist but still facing issue 

the same working fine in android

**Comment by da2gl** [comment]
@JiyadAhammad Hello. Can you attach the error log? Thank you.

**Comment by JiyadAhammad** [comment]
Sort the Problem by reducing the number of dependency added in pod file 
its solve my issue
