### ISSUE TITLE
onRewardedVideoShowFailed While click on reward ads ios

### ISSUE THREAD

**Issue by JiyadAhammad** [appodeal/Appodeal-Flutter-Plugin#79]
While my app is initializing, reward ads are loading and I'm receiving
onInitializationFinished: errors - 0

While clicking the rewards advertisements button on an Android device, it functions properly; however, on an iOS device, the onRewardedVideoShowFailed method is triggering. 

It occasionally works and occasionally doesn't for both iOS and Android.

**Comment by da2gl** [comment]
Hi @JiyadAhammad.
You can contact [our support team](https://faq.appodeal.com/en/articles/96628-technical-support).
They will help with solving your issue with onRewardedVideoShowFailed callback.
Have a nice day.
