### ISSUE TITLE
How to conditionally show ATT prompt after GDPR Consent Form?

### ISSUE THREAD

**Issue by jhe-efficial** [appodeal/Appodeal-Flutter-Plugin#80]
Hi, I'm using the Stack Consent Manager of the Appodeal-Flutter-Plugin and have configured both the GDPR and ATT message in AdMob. The GDPR Consent Form and the ATT Message are automatically displayed during SDK initialization, so everything works as expected. However, during my latest review by Apple, the following issue was raised:

_"The app includes a GDPR prompt and an App Tracking Transparency permission request, but they are implemented in a way that might confuse the user._
_Specifically, the app shows the App Tracking Transparency permission request after the user has already requested you not to track on the GDPR prompt._

_Next Steps:_
_If the user denies permission to track once, do not ask them to allow tracking again within the same permission request flow. There should be no tracking activity until the user grants permission to track._
_If the app shows the GDPR prompt before showing the App Tracking Transparency permission request, there is no need to modify the wording of the GDPR prompt."_

Is there a way to fulfill the requirements set by Apple with the Stack Consent Manager and display the ATT depending on the GDPR Consent result? Any help or hint is highly appreciated!

**Comment by da2gl** [comment]
Hi @jhe-efficial.
You can contact [our support team](https://faq.appodeal.com/en/articles/96628-technical-support).
They will help with solving your issue with consent logic.
Have a nice day.
