### ISSUE TITLE
There is a casting error in the AppodealPlayStorePurchase log event when sending an integer from Dart to Kotlin code

### ISSUE THREAD

**Issue by mrgzi** [appodeal/Appodeal-Flutter-Plugin#81]
The error occurs for the `purchaseTimestamp` value. Here are the detailed logs

`
E/MethodChannel#appodeal_flutter(17942): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#appodeal_flutter(17942): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#appodeal_flutter(17942): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#appodeal_flutter(17942): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#appodeal_flutter(17942): 	at android.os.Handler.handleCallback(Handler.java:958)
E/MethodChannel#appodeal_flutter(17942): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#appodeal_flutter(17942): 	at android.os.Looper.loopOnce(Looper.java:257)
E/MethodChannel#appodeal_flutter(17942): 	at android.os.Looper.loop(Looper.java:368)
E/MethodChannel#appodeal_flutter(17942): 	at android.app.ActivityThread.main(ActivityThread.java:8826)
E/MethodChannel#appodeal_flutter(17942): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#appodeal_flutter(17942): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
E/MethodChannel#appodeal_flutter(17942): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

I/flutter (29485): ERROR: PlatformException(error, java.lang.Long cannot be cast to java.lang.Integer, null, java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
I/flutter (29485): 	at com.appodeal.appodeal_flutter.AppodealFlutterPlugin.validateInAppPurchase(AppodealFlutterPlugin.kt:375)
I/flutter (29485): 	at com.appodeal.appodeal_flutter.AppodealFlutterPlugin.onMethodCall(AppodealFlutterPlugin.kt:97)
I/flutter (29485): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
I/flutter (29485): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
I/flutter (29485): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
I/flutter (29485): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
I/flutter (29485): 	at android.os.Handler.handleCallback(Handler.java:958)
I/flutter (29485): 	at android.os.Handler.dispatchMessage(Handler.java:99)
I/flutter (29485): 	at android.os.Looper.loopOnce(Looper.java:257)
I/flutter (29485): 	at android.os.Looper.loop(Looper.java:368)
I/flutter (29485): 	at android.app.ActivityThread.main(ActivityThread.java:8826)
I/flutter (29485): 	at java.lang.reflect.Method.invoke(Native Method)
I/flutter (29485): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
I/flutter (29485): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
I/flutter (29485): )
I/flutter (29485): 
I/flutter (29485): STACK:#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
I/flutter (29485): 1     MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
I/flutter (29485): <asynchronous suspension>
I/flutter (29485):
`

**Comment by da2gl** [comment]
Hi @mrgzi.
We will review your pull request as quickly as possible. Thank you.
Have a nice day.

**Comment by AntonZarytski** [comment]
Hi @mrgzi. 
I fixed this cast error here https://github.com/appodeal/Appodeal-Flutter-Plugin/pull/83

We will make this change in the next release, which will take place next week.
