### ISSUE TITLE
SDK not working

### ISSUE THREAD

**Issue by alex9153** [appodeal/Appodeal-Flutter-Plugin#84]
Error while initialization.
This is strange error because I'm not using google ads. And SDK tries init google 

E/AndroidRuntime(11858): FATAL EXCEPTION: main
E/AndroidRuntime(11858): Process: com.homm.cgames.app, PID: 11858
E/AndroidRuntime(11858): java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
E/AndroidRuntime(11858): 
E/AndroidRuntime(11858): ******************************************************************************
E/AndroidRuntime(11858): * Invalid application ID. Follow instructions here:                          *
E/AndroidRuntime(11858): * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
E/AndroidRuntime(11858): * to find your app ID.                                                       *
E/AndroidRuntime(11858): * Google Ad Manager publishers should follow instructions here:              *
E/AndroidRuntime(11858): * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
E/AndroidRuntime(11858): ******************************************************************************
2
E/AndroidRuntime(11858): 
E/AndroidRuntime(11858): 	at android.app.ActivityThread.installProvider(ActivityThread.java:8381)
E/AndroidRuntime(11858): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7881)
E/AndroidRuntime(11858): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7630)
E/AndroidRuntime(11858): 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
E/AndroidRuntime(11858): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2410)
E/AndroidRuntime(11858): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(11858): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(11858): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(11858): 	at android.app.ActivityThread.main(ActivityThread.java:8810)
E/AndroidRuntime(11858): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11858): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
E/AndroidRuntime(11858): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
E/AndroidRuntime(11858): Caused by: java.lang.IllegalStateException: 
E/AndroidRuntime(11858): 
E/AndroidRuntime(11858): ******************************************************************************
E/AndroidRuntime(11858): * Invalid application ID. Follow instructions here:                          *
E/AndroidRuntime(11858): * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
E/AndroidRuntime(11858): * to find your app ID.                                                       *
E/AndroidRuntime(11858): * Google Ad Manager publishers should follow instructions here:              *
E/AndroidRuntime(11858): * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
E/AndroidRuntime(11858): ******************************************************************************
2
E/AndroidRuntime(11858): 
E/AndroidRuntime(11858): 	at com.google.android.gms.ads.internal.client.zzek.attachInfo(com.google.android.gms:play-services-ads-lite@@23.0.0:15)
E/AndroidRuntime(11858): 	at com.google.android.gms.ads.MobileAdsInitProvider.attachInfo(com.google.android.gms:play-services-ads-lite@@23.0.0:1)
E/AndroidRuntime(11858): 	at android.app.ActivityThread.installProvider(ActivityThread.java:8376)
E/AndroidRuntime(11858): 	... 11 more

**Comment by da2gl** [comment]
@alex9153 Hi, please, read information about [Admob setup](https://github.com/appodeal/Appodeal-Flutter-Plugin/?tab=readme-ov-file#admob-configuration).
You can also contact [our support team](https://faq.appodeal.com/en/articles/96628-technical-support).
